### ISSUE TITLE
Does `DivisiveAction` make sense?

### ISSUE THREAD

**Issue by duairc** [tonyday567/numhask#158]
Currently `DivisiveAction` is defined as follows:

```haskell
class Divisive a => DivisiveAction m a | m -> a where
  (./) :: a -> m -> m
  (/.) :: m -> a -> m
```

I should add a disclaimer that I don't really know what a ¨divisive action" is in abstract algebra, I'm just trying to imagine what types I could fit into this typeclass.

Basically, I think `./` and `/.` are really quite separate concepts and don't belong in the same type-class. `/.` to me is more of a `MultiplicativeAction` thing, i.e.:

```haskell
(/.) :: (MultiplicativeAction m a, Divisive a) => m -> a -> m
a /. b = a *. recip b
```

So that would leave `DivisiveAction` with just `./`. A concrete example of what I think that could be is `(./) :: Area -> Length -> Length`. However I can't define that instance if I also need to define `(/.) :: Length -> Area -> Length`, because that doesn't make any sense.

By the way, this also applies to `SubtractiveAction` as well; I think `-.` is more of an `AdditiveAction` thing

```haskell
(-.) :: (AdditiveAction m a, Subtractive a) => m -> a -> m
a -. b = a +. negate b
```

What do you think?

**Comment by tonyday567** [comment]
Initial disclaimer that I just made up the 'divisive action' term.

In my mind both `./`and `/.` are multiplicative action things to use your example. The term 'scalar' is usually associated with multiplication but, in programming, you often find yourself adding (or dividing or subtracting) in exactly the same manner as scalar multiplying, and these other operators are just meant to represent these situations.

So, to modify your example, the class intension  was more `(./) :: Length -> Area -> Area` than the way you're thinking about it.

To speculate, and I've been trying to catch up on a bit of category theory, I think you're reaching for a notion of quotienting. I haven't thought on how to best express that in Haskell, but it's a nice thought.

Regardless, since I intend `*.` to mean `flip .*`, these extra operators should belong outside the class definition. This is a general flaw of the library I've been meaning to correct for some time.

**Comment by duairc** [comment]
The distinction I'm making between `./` and `/.` is that you can easily define `/.` in terms of `*.` (as I've shown), I don't see how you can define `./` in terms of `.*` in an analogous way, which to me suggests that it's something different (it's certainly not `flip (/.)`).

**Comment by tonyday567** [comment]
Confused. Why not `a ./ b = recip a .* b`?

**Comment by duairc** [comment]
Take [this `DivisiveAction` instance](https://github.com/tonyday567/numhask-space/blob/fa8c737a1ab4d4786205d64e2f8a9c89377405a5/src/NumHask/Space/Point.hs#L154-L156) from your `numhask-space` project. In particular, these definitions:

```haskell
  (.*) a (Point x y) = Point (a * x) (a * y)
  (./) a (Point x y) = Point (a / x) (a / y)
```

Your suggestion that `a ./ b = recip a .* b` doesn't work here.

Under the current definitions, the RHS would expand to `Point (recip a * x) (recip a * y)`, but the LHS would expand to `Point (a / x) (a / y)`, which can be rewritten `Point (a * recip x) (a * recip y)`. You can see that the `recip` ends up in a different place.

**Comment by tonyday567** [comment]
ok, I see it, the recip is in the module element. Told you I was confused!

I agree with your argument.

So, a plan of action would be:

- remove (/.) and (-.)
- pull (*.) and (+.) outside of the class definition.

**Comment by duairc** [comment]
Yes, I agree with that plan! Though I would keep `/.` and `-.` around (outside the class definition) as I've defined them above.

**Comment by duairc** [comment]
Thanks for fixing this!
