### ISSUE TITLE
Remove `Additive` requirement for `Epsilon`?

### ISSUE THREAD

**Issue by ocharles** [tonyday567/numhask#161]
I'd like to add an `Epsilon` instance for `linear`s `Point f a` type, but doing so requires an `Additive (Point f a)` instance. I can't write this instance, as `Point`s are not `Additive`. Is `Additive` a necessary superclass?

**Comment by tonyday567** [comment]
Hi Ollie,

Short answer is I think it is.

I spent a bit of time trying to imagine an instance or usage of Epsilon where the concept of additive is absent. I concluded that smallness and addition are closely related, but this could be due to a lack of imagination, and would look forward to any counter examples.

So the rest of this answer interprets your question as "can I just use the reality that Point has a Num Superclass instance instead of having to supply a (numhask) Additive instance?"  

The `Additive` constraint is equivalent to a `Num` constraint in base (or linear). The numhask classes are intended to be complete replacements for the `Num` class, together with a few bits and bobs that I think would be included in Prelude if the `Num` heirarchy was more principled, such as Epsilon and Direction.

The decision to squish together (+) and zero pushes the library away from automatic instances such as `instance (Num a) => Additive a` which are usually pretty dangerous.

The library could supply a module, NumHask.Num, say, that contained versions of things like Epsilon utilising Num rather than Additive and related classes. I'd think about splitting NumHask.Algebra.Metric out, and look to outsource the lattice, which would leave just the Prelude/base replacement bits as numhask.

I'm not totally across linear, but the instance would look something like:

```
import Prelude as P
import Linear.V2
import Linear.Affine
import qualified Linear.Vector as V
import NumHask.Prelude as N

instance (V.Additive f, Num a, Num (f a)) => Additive (Point f a) where
  (+) = (P.+)
  zero = V.zero
```

**Comment by ocharles** [comment]
Hey Tony, thanks for the detailed response! I thought about this some more and I actually think the types are right and I'm wrong - I now don't think it makes sense for `Point`s to have an `Epsilon` instance. `Point`s are "vectors that have forgot their origin", and as such it doesn't make sense to say "is this point near zero" because there is _no zero_! It's tempting to say 0 is the point that is 0 in all dimensions, but that's arbitrary.

So as such I think this instance is fine. What I should do is instead view a point as a vector from a fixed origin and then use `Epsilon` on that.

**Comment by tonyday567** [comment]
Practically, I tend to opt for a more coding-centric approach: a Point type as an XY coordinate pair eg where should I put this red pixel.

I agree with your 'near zero' metaphor. Depending on your usage, however, Epsilon can make sense for an affine space-style point. 

```
Thus it makes sense to subtract two points of the space, giving a translation vector, but it does not make sense to add two points of the space. ~ [affine space wiki](https://en.wikipedia.org/wiki/Affine_space)
```

I find this a good reminder of how you can't shoehorn everything into a heirarchy. Something that is ok for subtraction but not for addition tends to blow up the idea behind a principled type class structure.

Anyways, what you would be doing with an Epsilon in an affine space is representing a very small translation vector aka Euclidean distance.

https://hackage.haskell.org/package/hgeometry-0.13/docs/Data-Geometry-Point.html is a good reference.
