### ISSUE TITLE
Bad Subtractive instance for Bool?

### ISSUE THREAD

**Issue by wygulmage** [tonyday567/numhask#164]
`Subtractive` requires that `negate x + x == zero`, but `not x || x == True`.

As far as I know, `Bool` is only `Subtractive` when you define `+` as `/=` (XOR) and `negate` as `id`.

**Comment by tonyday567** [comment]
Yes, of course!

https://www.researchgate.net/publication/351103338_Boolean_Subtraction_and_Division_with_Application_in_the_Design_of_Digital_Circuits

This paper is quite an interesting take on what subtraction and division could be in the Boolean domain, as reversible addition and multiplication.

I've just glanced at it, but I especially like the idea expressed in the latter half that, if you multiply by zero, you should keep the other operand around, and then if there is a subsequent divide by zero, then you can return said operand, rather than NaN.

**Comment by wygulmage** [comment]
I'm not sure how that would help with the `Bool` instance in Haskell. You'd have to create your own "Boolean" data type with a constructor that stores indeterminate forms.

For `Bool` type, you may be best off either sticking with the standard Boolean ring (which is lawful although sometimes surprising, e.g. `negate = id`), or using the Boolean lattice operations as you have done, but keeping it as a semiring rather than including law-breaking negation.

You already have the lattice structure defined in `Algebra.Lattice`. I don't see a class for complemented lattices, but that's probably where `not` would belong.

The most orthogonal is probably the ring `(*) = (&&); (+) = (/=); one = True; zero = False; (-) = (+)` and the complemented lattice `(/\) = (&&); (\/) = (||); top = True; bot = False; complement = not`. But that would also be the largest change from your current definitions.

**Comment by tonyday567** [comment]
I went with removal of the Subtractive instance, and stuck with the existing setup.

If the library has a bias, it's towards coder sensibilities. True as 1 and False as 0 are fairly hard-wired in to practice, and I think it then follows, firstly, that True is the Multiplicative unit and False the Additive one, and then, consequently (by virtue of squishing (+) and zero into the one class), addition must be (||) and multiplication (&&).

I think your orthogonal ring is quite interesting, and it bothers me that the library can't handle it, but you can't cover everything.

Thanks for the issue!
