### ISSUE TITLE
Add rationals

### ISSUE THREAD

**Issue by ocramz** [tonyday567/numhask#31]
Support for `Ratio Int` etc. would be very handy in all situations that don't require exponential or trigonometric functions

**Comment by tonyday567** [comment]
Yep, for sure.

I was waiting around for a reason to add a whole bunch of numeric types.  Is that time now?

- Int8 to Int64
- Words
- Enum
- Char
- Scientific
- Rational

There are dozens more in base - pointers and c versions and wrapped monoids like (Max a), but that's where I thought you get to to cover 99% usage.

And then resolve what to do about RealFloat, Real and Fractional equivalents.

**Comment by ocramz** [comment]
Hmm, I'd say:

* IntX, WordX and Char types are easy
* Literals in scientific notation are best handled with `scientific`, which is a great library, but that means an extra dependency 
* NumHask rationals could be done by importing `Ratio` and friends from here (http://hackage.haskell.org/package/base-4.11.1.0/docs/src/GHC.Real.html#Ratio)

**Comment by tonyday567** [comment]
#39 adds fromRational functionality, adds the extra numeric types (Word, WordX and IntX) and fixes the tests  `abs (-128 :: Int8) == -128` can you believe!

What it doesn't do is actually add Ratio instances yet, because there's a pesky Integral constrain coming from base and it clashes with the numhask one.  Have to drop down into Data.Real and grab gcd, lcd etc in order to work around this.

**Comment by ocramz** [comment]
@tonyday567 what do you think of rewriting this, which comes from GHC.Real:

```
-- | @since 2.0.1
instance  (Integral a)  => Num (Ratio a)  where
    {-# SPECIALIZE instance Num Rational #-}
    (x:%y) + (x':%y')   =  reduce (x*y' + x'*y) (y*y')
    (x:%y) - (x':%y')   =  reduce (x*y' - x'*y) (y*y')
    (x:%y) * (x':%y')   =  reduce (x * x') (y * y')
...
```

where

```
reduce ::  (Integral a) => a -> a -> Ratio a
reduce _ 0              =  ratioZeroDenominatorError
reduce x y              =  (x `quot` d) :% (y `quot` d)
                           where d = gcd x y

gcd             :: (Integral a) => a -> a -> a
{-# NOINLINE [1] gcd #-}
gcd x y         =  gcd' (abs x) (abs y)
                   where gcd' a 0  =  a
                         gcd' a b  =  gcd' b (a `rem` b)

```

in terms of MultiplicativeGroup etc.
However for the concrete implementation of `quotRem` we will need to import `integer-gmp`: https://hackage.haskell.org/package/integer-gmp-1.0.2.0/docs/GHC-Integer.html

**Comment by tonyday567** [comment]
I think that's the go.

I haven't added quotRem into the interface, mostly so there's one less moving part, but also because divMod seemed to be better.  But it is faster ...

I couldn't work out whether integer-gmp is the default in base - the flag in base seems to be disabled but what is the default?  Regardless, am picking up the Integer divMod from Prelude.

**Comment by tonyday567** [comment]
#43 closes
