### ISSUE TITLE
Dimensions ops

### ISSUE THREAD

**Issue by o1lo01ol1o** [tonyday567/numhask#38]
I've been working on [an AD DSL based on the numhask hierarchy and array api](https://github.com/o1lo01ol1o/diffhask) and now that I'm filling out the numeric instances for `numhask-array` I'm finding that many type-level `dimensions` operations (transpose, tensor-product, etc) will need to be duplicated between the two packages.  I propose we talk to @achirkin about making a common package of `[Nat]` based operations going forward.

**Comment by achirkin** [comment]
I am happy to help if I can :)

**Comment by o1lo01ol1o** [comment]
I think the way forward would be to move [the numhask-array operations](https://github.com/tonyday567/numhask/blob/master/numhask-array/src/NumHask/Array/Constraints.hs) to a new project

@tonyday567 What do you think if @achirkin initializes a `dimensions-ops` repo or similar?

**Comment by achirkin** [comment]
Hmm, I see this project uses `singletons` package a lot, so it might be costly to adapt it to`dimensions`. Even though `singletons` is a great and comprehensive package, I do not use it in `dimensions` to minimize dependencies (especially to avoid TH). As a result, it is not compatible at all.
On the good side, I think there is no need in a separate `dimensions-ops`, since most of functions from the module you mentioned is in `dimensions` already.

**Comment by tonyday567** [comment]
I'm keen to remove the singletons dependency from here for the same reasons - just got stuck in how to best go about this. So, yes, NumHask.Array.Constraints needs to be switched to dimensions in its entirety.

numhask-array is in this repo because the base library is undergoing a lot of dev, so it's easier to make changes across libraries.  I'm finding that the subrepo thing works well, and happy to make a new one, or we can rip it out and make a new repo if that's easier for development purposes.

**Comment by achirkin** [comment]
Then I would suggest you to try using `dimensions` in place of `singletons` and then I will implement missing functionality based on your emerging requirements :)
@o1lo01ol1o I implement some linear algebra ops like [products](https://github.com/achirkin/easytensor/blob/crazy/easytensor/src/Numeric/DataFrame/Contraction.hs#L58) and [other ops on multidimensional frames](https://github.com/achirkin/easytensor/blob/crazy/easytensor/src/Numeric/DataFrame/SubSpace.hs) together with other [matrix](https://github.com/achirkin/easytensor/blob/crazy/easytensor/src/Numeric/Matrix/Class.hs) and [quaternion](https://github.com/achirkin/easytensor/blob/crazy/easytensor/src/Numeric/Quaternion/Class.hs) operations useful for graphics applications  in `easytensor` package, but that one might be not suitable for your needs. The most important part of it is [dealing with sub-frames](https://github.com/achirkin/easytensor/blob/crazy/easytensor/src/Numeric/DataFrame/SubSpace.hs), so you may want to adapt the type signatures of `SubSpace` operations to your array implementations.

Note, I am working on branch `crazy` lately, which is a major rework of the whole project. Will merge it into `master` this or next week and update it on hackage.

**Comment by o1lo01ol1o** [comment]
https://github.com/o1lo01ol1o/diffhask/issues/8

**Comment by o1lo01ol1o** [comment]
unblocks: https://github.com/o1lo01ol1o/diffhask/issues/8

**Comment by tonyday567** [comment]
Closing,, see https://github.com/tonyday567/numhask-array
