### ISSUE TITLE
Create NumHask instances for Interval class

### ISSUE THREAD

**Issue by tonyday567** [tonyday567/numhask#44]
https://hackage.haskell.org/package/intervals-0.8.1/docs/Numeric-Interval.html

IEEE numbers, floats and doubles, fail many of the current tests, such as associativity, and they fail by an arbitrary size, so that Epsilon instances can't help create approximate relationships.

The solution is creating Numeric.Interval instances for the numhask tower.  We can then test for laws on IEEEs by creating an interval that wraps an arbitrary float (say) in plus or minus `epsilon`, and test whether the results fall within that interval.

The hard part of the exercise is deciding what to do about orphans: do we hook into Numeric.Interval and create orphan instances or start from scratch and create a NumHask.Interval?

**Comment by tonyday567** [comment]
https://www.reddit.com/r/haskell/comments/8pj3na/convenient_intervalinterface_possible/

**Comment by LeanderK** [comment]
I created the reddit thread. It's related to refinement types, something like this: https://www.reddit.com/r/haskell/comments/8rj1gy/smart_constructors_that_cannot_fail/ is relevant.

I don't think we'll get accurate Domains of our function until we have dependent types thought (because nearly about them is dependently typed).

I could tackle this after #76 is done, I don't expect it to be much work.

**Comment by tonyday567** [comment]
#109 closes
