### ISSUE TITLE
Add LogFloat

### ISSUE THREAD

**Issue by ocramz** [tonyday567/numhask#54]
This would be a perfect use-case for non-Num properties.

see e.g. 

https://hackage.haskell.org/package/logfloat-0.13.3.3/docs/Data-Number-LogFloat.html

**Comment by ocramz** [comment]
I should specify that the need for this construction comes from statistics; for example when computing the likelihood of some parameter with an IID dataset of size N, one has to multiply N tiny floats, which usually causes a floating point underflow. The fix is usually to sum log-probabilities.

**Comment by tonyday567** [comment]
Hi @LeanderK,

Yes a more polymorphic version: anything that has an ExpField instance, I presume.  Maybe LogField is the right name.

We might have to do some slight surgery on the module tree in the core numhask library.  `Rational` is the other example of a number starting from scratch in numhask and it's probably misplaced.  It might be better to have `NumHask.Data.LogField` and `NumHask.Data.Rational`.

**Comment by LeanderK** [comment]
Hi! 🙂
Ok, I think I get it. Makes sense.

I would clearly separate the algebra stuff from the defined data-datatypes. `NumHask.Data` seems like a better place.

**Comment by LeanderK** [comment]
Question: What to do about `isNaN`? It's used in `LogFloat` a number of times to give better error messages, but @tonyday567 removed it in https://github.com/tonyday567/numhask/commit/23748d2c6d24c2144cc01bae31cfceff0c2dec6d.

Ideally, it shouldn't matter, but the implementation of the hierarchy doesn't really reflect the fact that log is only defined for positive numbers.

**Comment by tonyday567** [comment]
I removed `isNaN` because I started to think of it as an IEEE requirement, rather than anything that is strictly mathematically inherent.  Specifically, IEEE requires a float nan to satisfy nan == nan ===> False.  I think we can get away with it because isNaN is supplied by base for double and float already, so we don't have to reproduce.  Maybe the introduction of LogFloat means we can't get away from that logic in this instance.

More generally, I have been steering towards total functions and away from exceptions, and nan represents a way to do that.  I like thinking that log(zero) = infinity, and log(-1) = nan.

We could only defined log for positive numbers, via defining positive numbers, but this would mean that we could never take the log of a double.  That feels to me too far away from current practice. Compared with maths, Haskell feels biased towards providing homomorphic functions.  Another example is `abs` which should more strictly be `abs :: (AdditiveUnital a) => a -> Positive a`. 

HOWEVER, I am probably avoiding exceptions because I have never bothered to learn about them.  Very open to alternative approaches.

**Comment by LeanderK** [comment]
hmm, well it's your library, but I am not a fan of `NaN`s. I view them more like null-pointer and they can cause some serious issues if they pop up unexpectedly.
I don't think `log(-1) = nan` is a great solution.

I agree that `NaN` is a bit weird, but I would definitely include `isNan` if `nan` could pop up, otherwise there is no way to deal with it. That's gonna bite us later.

I would really like to express `log : (0, inf) -> R`, because then we really have a more type-safe numerical code. But I don't know how the ergonomics could work out and therefore I think this a completely different issue.

**Comment by LeanderK** [comment]
But another problem popped up. Because I don't keep track of the sign, I can't implement `negate` and therefore `substract`. Is this an issue?

**Comment by tonyday567** [comment]
> hmm, well it's your library, but I am not a fan of NaNs

Your library too!  We should put isNaN back in for sure.  Let's make nan mean exactly `0/0`.  I can't unsee the null you point out.

(0,inf) is [here](https://github.com/tonyday567/numhask/blob/master/numhask-prelude/src/NumHask/Examples.hs#L131)!  It needs a proper constructor that throws an exception on `Positive (-1)` say, but otherwise it seems pretty sweet.  we should ditch the AdditiveInvertible instance.

**Comment by tonyday567** [comment]
power is [here](https://github.com/tonyday567/numhask/blob/master/numhask/src/NumHask/Algebra/Field.hs#L82) but named (**).

We should add these to ExpField

    log1p x = log (1 + x)
    expm1 x = exp x - 1
    log1pexp x = log1p (exp x)
    log1mexp x = log1p (negate (exp x))

**Comment by tonyday567** [comment]
I've gone back and forth on an AdditiveGroup instance in terms of design and supporting positive numbers.  I can imagine allowing the use of (-) and throwing an error if the result is negative, but you can't implement this given the existing structure, as negate is used in defining (-).

Let's go with no negate, and no subtract or (-).

**Comment by LeanderK** [comment]
Can I remove the `AdditiveGroup` requirement for `Epsilon`?
https://github.com/tonyday567/numhask/blob/48ebf662ea9894866422f3e92fb6031e868b3fc1/numhask/src/NumHask/Algebra/Metric.hs#L309
I don't think it's needed anyway.

**Comment by tonyday567** [comment]
Sure.  You just have to put aboutEqual outside the class (where the AdditiveGroup is needed).

**Comment by tonyday567** [comment]
It's not that you need it.  AdditiveGroup can't be removed because of the pesky (-) in aboutEqual and aboutEqual is used in a lot of places.

**Comment by LeanderK** [comment]
The thing is that I can implement `aboutEqual` for `LogField`, but I can't implement a general `-`. I just have to replace the default implementation for the typeclass.
I'll make a commit later this day, then I can show you what I mean.

**Comment by tonyday567** [comment]
#66 closes
