### ISSUE TITLE
Mash together *Invertible and *Group ?

### ISSUE THREAD

**Issue by ocramz** [tonyday567/numhask#61]

**Comment by ocramz** [comment]
but a group doesn't need to be commutative; that's the definition of an Abelian group.

A group has : 
* Identity element
* Inverse element
* Associative binary operation

Or am I missing something? I could certainly use some counterexamples here.

**Comment by tonyday567** [comment]
Cool, that's a definite correction needed.

It has a lot of knock on effects, so may as well review the lot.  Here's a candidate list we can toss about:

- drop the convention that (+) means commutative, and remove `plus` 
- make Additive the first level, and this means Associative and Unital - this runs against some definitions of addition, but places it squarely as a Monoid (which is the current definition in base of Sum right?).  So zero and (+) as the two operators.
- AdditiveGroup ==> Additive + negate.  No AdditiveInvertible.
- AdditiveCGroup ==> AdditiveGroup + Commutative.  Not Abelian because this implies Addition Group and the prefix doesn't translate upstream (MultiplicativeAbelian, AbelianRing etc would add to confusion).
- Can we get away with dropping the magmas, and the base classes?  AdditiveAssociative and AdditiveUnital are semigroup and monoid specialisations, I think @kmett might be getting ready to add Commutative to base (eventually).  Just need to keep AdditiveIdempotent, which then needs to be also unital and associative (since it's using the (=) operator).

https://en.wikipedia.org/wiki/Distributive_property

- Distribution is wrong, because it doesn't need to be commutative, so the Additive change fixes.  Multiplication just needs to be a magma, however, so we are adding some unnecessary laws.
- What we also have here is ArithmeticDistribution ((*) over (+)) and we need to abstract it if we are going to deal with Lattices etc.
- Then Distribution (*) (+) => Semiring + AdditiveGroup (-) => Ring
- But then how do we add Commutative to make a CRing?  Gut feel is that we should be able to generalise Commutative.
- Is a Field necessarily commutative?

**Comment by LeanderK** [comment]
I don't think it's a good Idea to reduce the hierarchy too much. There are many useful examples that can't be expressed with an ambitious reduction. For example:
> make Additive the first level, and this means Associative and Unital - this runs against some definitions of addition, but places it squarely as a Monoid (which is the current definition in base of Sum right?). So zero and (+) as the two operators.

What about additive stuff without identity-elements? An immediate example would a range without 0 (like `[1,10]`). If we also drop the `AdditiveMagma`, there's no way to do this.

**Comment by LeanderK** [comment]
@tonyday567 i think the magma Hierarchy is very useful!! it's just laying waste right now!

**Comment by tonyday567** [comment]
I think we've well adressed this, and the code base has moved on.
