### ISSUE TITLE
Redefine the Metric class

### ISSUE THREAD

**Issue by JamieBallingall** [tonyday567/numhask#81]
The definition of the Metric class currently reads:
https://github.com/tonyday567/numhask/blob/405904fbbe8b2fe45bb952bdacf081e79a527418/numhask/src/NumHask/Algebra/Metric.hs#L220-L230
In discussions of a PR, @ocramz raises concerns, including:
- Not all metric spaces are induced by a Lebesgue norm
- A "metric" over a set X is usually taken to be a binary function X * X -> R+ that's:
  - non-negative
  - commutative
  - sub-additive

This hints at a Metric typeclass that defines a single distance metric. Many sources ([Wikipedia](https://en.wikipedia.org/wiki/Metric_space#Definition), [Mathworld](http://mathworld.wolfram.com/MetricSpace.html)) include "identity of indiscernibles" as an axiom:
`d x y == 0` implies and is implied by `x == y`
and note that non-negativity can be proved from the other axioms.

While most sources do define the distance as a function `X -> X -> R+`, I think that is difficult for us because we don't have a "true" representation of the reals, but multiple approximations (e.g., Rationals or Doubles).

I propose redefining the Metric typeclass to a single distance function of type `a -> a -> b`, stating axioms of identity of indiscernibles, commutativity and sub-additivity and with a comment that this implies non-negativity.

**Comment by tonyday567** [comment]
I have been cautious so far in moving away from base, with its `abs :: a -> a` assumption as built in to Num, but it feels like correctness and type safety is more important.

Performance is my main concern. Do we have a zero cost conversion from R+ back to X  (or your polymorphic b back to a)?  A `hom a = coerce a`?

Otherwise, a big thumbs up from me on this proposal.

In thinking this through, can we include consideration of Sign (which contain the abs and sign operators).  There was also an idea floating around that metric belongs elsewhere - like numhask-metric - but this may fade away with #76

**Comment by LeanderK** [comment]
I am (in secrect 😀) working on a more "rigorous" linear algebra library on top of numhask. It replaces some of the the typeclasses and adds a lot more.

I formulated a more serious Metric there, but we buy the flexibility with complexity! I've some attempts and think I found something conceptually rather simple, but to use it you need advanced GHC features 😕 (for example TypeApplications because you can't infer the metric most of the times).

**Comment by JamieBallingall** [comment]
@tonyday567 I'm not fully up to speed on performance in Haskell (if you'll excuse the pun). Does the typeclass definition itself affect performance. I'm imagining that
```
class Metric a b where 
  distance :: a -> a -> b 
```
gets instantiated in very concrete ways as, for example,
```
instance Metric Double Double where
  distance a b = abs (a - b)
```
Am I being naive?

**Comment by LeanderK** [comment]
You are partly right. But I could also define more general metrics, that take dictionaries defined via numhask. For example, the Abs-metric could use the Signed-typeclass.

This doesn't make any difference if distance get's inlined (the dictionary get's eliminated) and we really, really want to inline everythin in numerical code.

I think we could also define overlapping instances to specialize?

**Comment by tonyday567** [comment]
closed: reducing scope.
