### ISSUE TITLE
Define Natural, Real etc. via ToNaturalM etc.

### ISSUE THREAD

**Issue by LeanderK** [tonyday567/numhask#84]
I am working on https://github.com/hs-backbone/linear, which sits on top of numhask, and I have the problem that I need to be polymorphic for example over some kind of Natural Number (for example with the indexing-functionality for a Matrix or the return of `getDim`).

I think a good solution is to define them via Isomorphism from and to Natural, Real etc. The problem is that many backends can't express the naive formulation, for example Accelerate can't express:
```haskell
class ToInteger a where
   a -> Int
```
But I think every Backend should be able to express (since some need `IO` to compute):
```haskell
class ToIntegerM a where
   (Monad m) => a -> m Int
```
Independent of whether this is useful in its self (which I think it is!), it serves as a definition of Natural Numbers, Reals, Complexes etc.

**Comment by tonyday567** [comment]
`fromInteger` is hardcoded into the language itself - see rebindable syntax - so you have to have `fromInteger 3` mean `3 :: Int`, not `3 :: IO Int`.

What I have to do for [backprop](https://github.com/tonyday567/numhask-backprop/blob/master/src/NumHask/Backprop.hs#L24) is make FromInteger polymorphic in the second argument. Does a `FromInteger a b` help here?  It feels like you are proposing an instance `FromInteger a (m Int)` which would be a subset.

**Comment by LeanderK** [comment]
oh, I just noticed that I mixed up `From` an `To`. `FromInteger` is implementable for any backend (i think), but `ToInteger` is not!
Also, the usage of the typeclass is not to actually use the class much (the Monad is annoying), but more to define Natural Numbers, Rations etc via a bijection (assuming the implementations to be injective) with the `Monad m` constraint back.

**Comment by ocramz** [comment]
@LeanderK I don't understand the role of Monad here. Are you proposing something like `lift` in Accelerate? https://github.com/AccelerateHS/accelerate/blob/b291fb83589e5e0fc94db687a92badd1c1b9c7d9/src/Data/Array/Accelerate/Lift.hs#L98

**Comment by LeanderK** [comment]
More like `run` in Accelerate (although accelerate chose to use `unsafePerformIO`).

It's defined here: https://github.com/AccelerateHS/accelerate/blob/66385eabe6708c89e78455aad5491bfa86d72b11/src/Data/Array/Accelerate/Interpreter.hs#L94

**Comment by tonyday567** [comment]
I think you define the entire hierarchy within the context you need such as Accelerate.  So `instance (Unital (Sum a)) => Unital (Sum (Acc a))` etc.  So the raw numbers are `Acc a`'s.

Given that, we need something like `class ToIntegral a b where toIntegral :: a -> b` instead of ToInteger and it all works well.

The monad constraint you're thinking of is a red herring.  If you think about the operation in two steps: you put a number in a context (`a -> m a`), then you use the number within the context (`m a -> m a`).

This all has to fit in with base which insists the interface `fromInteger (1 :: Integer)`, so you have to say `class FromInteger a where fromInteger :: Integer -> a` and the instance is then `instance (FromInteger a) => FromInteger (Acc a) where fromInteger (Acc a) = Acc (fromInteger a)` or similar.

**Comment by LeanderK** [comment]
Hmm, I don't know whether this will work. `class ToIntegral a b where toIntegral :: a -> b` seems way to polymorphic.

The Idea of the type class is not to actually use it! We only need it because only Integer-like things can implement it. I know it's not useful for accelerate, but that's not the point I am trying to make.

I am thinking about how to otherwise force integers to be integers. The usual axiomatic encoding is the peano axioms, but I don't think that it can be implemented as a type-class so that only integer-like things have this interface.

`FromInteger` should not be a problem, I think every backend can implement it.

**Comment by tonyday567** [comment]
reducing scope
