### ISSUE TITLE
noun or adjective prefixes

### ISSUE THREAD

**Issue by tonyday567** [tonyday567/numhask#93]
I'm very resilient to the bike-shedding argument against getting naming conventions correct.

We have `NumHask.Algebra.Abstract.Additive` but the class it contains is `Addition`.  Should we go with:

- noun prefixure, so the class and module names should be `Addition`
- adjective prefixure, so class and module names are both `Additive`
- a mix to confuse everyone?

I'd like to apply this consistently to everything, so if its a yes to noun, for example, we change `NumHask.Data.Rational` to `NumHask.Data.Ratio`.

**Comment by ocramz** [comment]
I'd prefer the adjective style for both typeclasses and their modules they're defined in :)

**Comment by LeanderK** [comment]
I am on the fence about this. I am not sure whether I like Adjectives as Typeclass-Names (spontaneously, I would say I don't prefer them, but without a strong opinion). But I think we're more consistent if we chose not to. Because what happens when there's no obvious adjective?
What about `Group`, `Ring`, `Field`, `Module`? I think `Addition` fits nicer in there than `Additive`. 
`Base` is also not consistent with `Functor` and `Foldable`.

**Comment by ocramz** [comment]
I don't think there's any guideline; I think consensus and common sense are what guide the naming. Some libraries use the `Has`- or `Is`- prefix for typeclass names, but it would add a lot of noise here. When in doubt and if available, we should stick to the naming tradition that's already accepted in the most common Haskell libraries. I see a typeclass as a property of something, so calling something "a Monoid" is improper; a Monoid is an algebraic structure, but string concatenation and the empty string only define an _instance_ of that, i.e. witness that strings have that property.

**Comment by tonyday567** [comment]
#97 closes.  We can repaint the shed noun-ish next week!

I left HadamardMultiplication.  Strict OCD suggested MultiplicativeHadamard, but then would have had to say DivisiveHadamard ???
